### ISSUE TITLE
Speedy Rendering causing choppy JS animation and wasting CPU

### ISSUE THREAD

**Issue by WAZAAAAA0** [eladkarako/chrome_extensions#13] opened 2019-11-24 18:13 UTC
Tested on both Firefox and Chrome on this specific website https://web.archive.org/web/20191023081521/https://animejs.com/

With the extension enabled, the animation looks very ugly and choppy, wasting twice as much CPU in the process.

**Comment by eladkarako** [comment] 2019-11-29 18:32
animejs uses a JavaScript timer, 
and writes the `style` attribute each time.
this causes a reflow and rendering uses a lot of CPU.

the web-extension speedy-rendering reduces the duration of transition animation 
(yes, it makes it ugly), so it will finish faster, 
this is useful in-cases such as Google-recaptcha, which uses transition to delay user delay (an annoy users as-well).

I personally prefer a pure-CSS based animation.

those effects you 'feel' are to be expected.

Note how the animation is finishes faster? also a lot of them finish very close to next one in line, 
so transition events (JavaScript) will fire more quickly. This explains the excessive CPU usage.

a developer of a website or a plugin might want to stick to keyframe animations, 
and maybe combine some tricks to try use GPU for some of the animations, as explained in here: https://blog.teamtreehouse.com/increase-your-sites-performance-with-hardware-accelerated-css 

I personally tried to embedded several of the tricks in the web-extension, 
but it won't work with every website, 
so I've generalized the solution (to what the speedy-rendering current injects).

Not A Bug (Won't Fix).

**Closed by eladkarako** 2019-11-29 18:32 UTC
Labels: NotBug, wontfix
